---
- name: "Set fqdn {{ fqdn | default(inventory_hostname) }}"
  hostname:
    name: "{{ fqdn | default(inventory_hostname) }}"
  ignore_errors: yes
  register: hostname_change

- name: Re-gather facts because hostname has been updated
  action: setup
  when: hostname_change.changed == "true" and hostname_change.failed == "false"

- name: Configure apt to minimize amount of instaled packages
  copy:
    src: debian-minimal
    dest: /etc/apt/apt.conf.d/00_only_required_packages
    mode: 0644
    owner: root

# Autoupdate
- name: Debian autoupdate
  include: autoupdate.yml
  when: autoupdate_enable == "true"

- name: Manage sshd
  include: sshd.yml

- name: Disable IPv6
  copy:
    src: noIPv6
    dest: /etc/modprobe.d/noIPv6
    mode: 0640
  when: disable_ipv6 == "true"

- name: Configure resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0444

- name: Configure bash
  copy:
    src: 00-custom_bash.sh
    dest: /etc/profile.d/00-custom_bash.sh
    mode: 0755
    owner: root

- name: Clean etc skel
  file:
    path: /etc/skel/.bashrc
    state: absent

- name: Copy vim configuration
  copy:
    src: vimrc
    dest: "{{ item }}"
    owner: root
  with_items:
  - /etc/vim/vimrc
  - /etc/vim/virc

- name: Rsyslog
  include: rsyslog.yml

- name: Update cache
  apt:
    update_cache: yes

- name: Install core packages
  apt:
    state: present
    name: "{{ core_packages }}"

- name: OS filesystem hardening
  include: perms.yml
  when: hardening_os == "true"

- name: Sysctl hardening
  template:
    src: sysctl.conf
    dest: /etc/sysctl.d/hardening.conf
    mode: 0640
  when: hardening_os == "true"
