- name: Reconfigure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0640
    backup: yes
    validate: 'sshd -T -f %s'

- name: Configure sshd service
  systemd:
    name: sshd
    state: reloaded
    enabled: yes

- name: Manage root's ssh keys
  block:
  - set_fact:
      root_key_list: "{{ lookup('file', item) }}"
    with_items: "{{ root_keys }}"
    register: root_key_list_out
  - set_fact:
      root_keys_string: "{{ root_key_list_out.results | map(attribute='ansible_facts.root_key_list') | list | join('\n') }}"
  - authorized_key:
      key: "{{ root_keys_string }}"
      state: present
      user: root
      exclusive: yes
  tags:
  - ssh_keys

