- name: Reconfigure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0640
    backup: yes
    validate: 'sshd -T -f %s'

- name: Configure sshd service
  systemd:
    name: sshd
    state: reloaded
    enabled: yes

